project:
  type: website
  output-dir: docs

website:
  title: "erica-bishop.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog_options.qmd
        text: Blog

format:
  html:
    theme: 
      - stylesheet.scss
    mainfont: Prata
    toc: true

editor: visual

